[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"

[rpc_endpoints]
evmixt = "https://k8s.testnet.evmix.json-rpc.injective.network"
devnet = "https://devnet.json-rpc.injective.dev"
