#TESTNET
# export NODE=https://k8s.testnet.evmix.json-rpc.injective.network
# export INODE=https://k8s.testnet.evmix.tm.injective.network
# export CHAIN_ID=injective-999
# export ADDR=0x847E60f16a6176FA0aF516c1aDf5364f699aEe83
# export ACC=0xAd012a44c12FAA19445eeae07097ff94E8A6592F
# export IACC=inj145qj53xp974pj3z7ats8p9lljn52vkf0ahewk2
# export ACC_NONCE=1
# export SUB_ACC_ID=0xAd012a44c12FAA19445eeae07097ff94E8A6592F000000000000000000000000
# export QUOTE=INJ

#LOCAL
export ETH_URL=http://localhost:8545
export INJ_URL=http://localhost:26657
export CHAIN_ID=injective-1

export USER=user1
export USER_MNEMONIC="copper push brief egg scan entry inform record adjust fossil boss egg comic alien upon aspect dry avoid interest fury window hint race symptom"
export USER_PWD=12345678
export USER_ETH_ADDR=0xC6Fe5D33615a1C52c08018c47E8Bc53646A0E101
export USER_INJ_ADDR=inj1cml96vmptgw99syqrrz8az79xer2pcgp0a885r

export QUOTE=inj

user-import:
	./scripts/user-import.sh

user-show:
	./scripts/user-show.sh

contract-create:
	./scripts/contract-create.sh

contract-fund:
	./scripts/contract-fund.sh

contract-balances:
	./scripts/contract-balances.sh

verify:
	./verify.sh

query-deposits:
	./scripts/account-query-deposits.sh

deposit:
	./scripts/account-deposit.sh 

withdraw:
	./scripts/account-withdraw.sh